apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 4  # More replicas for production
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:stable  # Use a stable image tag for production
